# Generated by Django 4.2.5 on 2023-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
